language: scala

scala: 2.11.7

jdk: oraclejdk8

env:
  - CODACY_PROJECT_TOKEN=86acc16c5a8046ff9a3ec4705919c696

script: ./build.sh

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt/boot

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/980748d83fc35b082c35
